services:
  auth-server:
    build: ./auth-server
    ports:
      - "4000:4000"
    volumes:
      - ./shared:/app/shared
      - ./shared/certs/ca.pem:/app/certs/ca.pem:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/app/certs/ca.pem

  service1:
    build: ./service1
    ports:
      - "5001:5001"
    depends_on:
      - auth-server
    volumes:
      - ./shared:/app/shared
      - ./shared/certs/ca.pem:/app/certs/ca.pem:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/app/certs/ca.pem

  service2:
    build: ./service2
    ports:
      - "5002:5002"
    depends_on:
      - auth-server
    volumes:
      - ./shared:/app/shared
      - ./shared/certs/ca.pem:/app/certs/ca.pem:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/app/certs/ca.pem

  client-app:
    build: ./client-app
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
    volumes:
      - ./shared:/app/shared
      - ./shared/certs/ca.pem:/app/certs/ca.pem:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/app/certs/ca.pem